name: Build Android APK

# This tells GitHub to run the script whenever you push new code, 
# or when you manually click a button.
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Android usually uses Java 11 or 17
        distribution: 'temurin'

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build the Debug APK
      run: ./gradlew assembleDebug

    - name: Upload the APK
      uses: actions/upload-artifact@v4
      with:
        name: My-Android-App
        path: app/build/outputs/apk/debug/app-debug.apk
